# V1: 1274 chars
import random as r;print('\n| Welcome to Sliding Puzzle!\n| Use WASD to move the empty tile.\n| Enter QUIT to exit.');input('| Press Enter to continue...');n=int(input('\nGrid Size: '));t=r.sample([str(i)+(' 'if len(str(i))==1 else'')for i in range(1,n*n)]+['  '],n*n);b=[[t[i*n+j]for j in range(n)]for i in range(n)];exec("import time\nwhile True:\n  h=('+'+'-'*6)*n+'+';v='|'+' '*6;l='|'+' '*2+'{}'+' '*2;s=''\n  for i in range(n):\n    s+=h+'\\n'+v*n+'|\\n'\n    s+=''.join(l.format(b[i][j])for j in range(n))+'|\\n'+v*n+'|\\n'\n  s+=h;print(s)\n  e=next((i,j)for i in range(n)for j in range(n)if b[i][j]=='  ')\n  v=[m for m,c in[('S',e[0]>0),('W',e[0]<n-1),('D',e[1]>0),('A',e[1]<n-1)]if c]\n  print(f\"{' '*25} ({'W'if'W'in v else' '})\");print(f\"Enter WASD (or QUIT): ({'A'if'A'in v else' '}) ({'S'if'S'in v else' '}) ({'D'if'D'in v else' '})\")\n  m=input('> ').upper()\n  if m=='QUIT':break\n  if m not in v:print('Invalid move. Try again.');time.sleep(1);continue\n  if m=='S':b[e[0]][e[1]],b[e[0]-1][e[1]]=b[e[0]-1][e[1]],b[e[0]][e[1]]\n  elif m=='W':b[e[0]][e[1]],b[e[0]+1][e[1]]=b[e[0]+1][e[1]],b[e[0]][e[1]]\n  elif m=='D':b[e[0]][e[1]],b[e[0]][e[1]-1]=b[e[0]][e[1]-1],b[e[0]][e[1]]\n  elif m=='A':b[e[0]][e[1]],b[e[0]][e[1]+1]=b[e[0]][e[1]+1],b[e[0]][e[1]]")

# V2: 1178 chars
import random as r;print('\n| Welcome to Sliding Puzzle!\n| Use WASD to move the empty tile.\n| Enter QUIT to exit.');input('| Press Enter to continue...');n=int(input('\nGrid Size: '));t=r.sample([str(i)+(' 'if len(str(i))==1 else'')for i in range(1,n*n)]+['  '],n*n);b=[[t[i*n+j]for j in range(n)]for i in range(n)];exec("while 1:\n h=('+'+'-'*6)*n+'+';v='|'+' '*6;l='|'+' '*2+'{}'+' '*2;s=''\n for i in range(n):s+=h+'\\n'+v*n+'|\\n'+''.join(l.format(b[i][j])for j in range(n))+'|\\n'+v*n+'|\\n'\n print(s+h);e=next((i,j)for i in range(n)for j in range(n)if b[i][j]=='  ')\n v=[m for m,c in[('S',e[0]>0),('W',e[0]<n-1),('D',e[1]>0),('A',e[1]<n-1)]if c]\n print(f\"Enter WASD (or QUIT): ({'W'if'W'in v else' '})({'A'if'A'in v else' '})({'S'if'S'in v else' '})({'D'if'D'in v else' '})\")\n m=input('> ').upper()\n if m=='QUIT':break\n if m not in v:print('Invalid move');continue\n if m=='S':b[e[0]][e[1]],b[e[0]-1][e[1]]=b[e[0]-1][e[1]],b[e[0]][e[1]]\n elif m=='W':b[e[0]][e[1]],b[e[0]+1][e[1]]=b[e[0]+1][e[1]],b[e[0]][e[1]]\n elif m=='D':b[e[0]][e[1]],b[e[0]][e[1]-1]=b[e[0]][e[1]-1],b[e[0]][e[1]]\n elif m=='A':b[e[0]][e[1]],b[e[0]][e[1]+1]=b[e[0]][e[1]+1],b[e[0]][e[1]]")

# V3: 529 chars
import random as r;n=int(input());t=r.sample([f"{i:<2}"for i in range(1,n*n)]+['  '],n*n);b=[[t[i*n+j]for j in range(n)]for i in range(n)];exec("while 1:\n print('+'+'--+'*n+'\\n'+''.join('|'+''.join(b[i][j]for j in range(n))+'|\\n'+'+'+'--+'*n+'\\n'for i in range(n)))\n x,y=next((i,j)for i in range(n)for j in range(n)if b[i][j]=='  ')\n d={'S':(-1,0),'W':(1,0),'D':(0,-1),'A':(0,1)};m=input().upper()\n if m=='Q':break\n if m in d and 0<=x+d[m][0]<n and 0<=y+d[m][1]<n:i,j=x+d[m][0],y+d[m][1];b[x][y],b[i][j]=b[i][j],b[x][y]")

# V4: 436 chars
import random as r;n=int(input());l=range(n);t=r.sample([f"{i:<2}"for i in range(1,n*n)]+['  '],n*n);b=[[t[i*n+j]for j in l]for i in l];exec("while 1:\n print('\\n'.join(''.join(r)for r in b))\n x,y=next((i,j)for i in l for j in l if b[i][j]=='  ')\n d={'s':(-1,0),'w':(1,0),'d':(0,-1),'a':(0,1)};m=input()\n if m=='q':break\n if m in d and 0<=x+d[m][0]<n and 0<=y+d[m][1]<n:(i,j)=(x+d[m][0],y+d[m][1]);b[x][y],b[i][j]=b[i][j],b[x][y]")

# V5: 3x3: 342 chars
import random as r;l=[0,1,2];t=r.sample([str(i)for i in range(8)]+[' '],9);b=[t[i:i+3]for i in [0,3,6]];exec("while 1:\n print('\\n'.join(''.join(r)for r in b))\n x,y=next((i,j)for i in l for j in l if b[i][j]==' ')\n m=input()\n i,j=x+{'s':-1,'w':1}.get(m,0),y+{'d':-1,'a':1}.get(m,0)\n if 0<=i<3 and 0<=j<3:b[x][y],b[i][j]=b[i][j],b[x][y]")